{{- if .Values.tests.install }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-tests-atp-storage-secret
  labels:
    {{- include "kubernetes.labels" . | nindent 4 }}
type: Opaque
stringData:
  atp-storage-username: {{ .Values.tests.atpStorage.username }}
  atp-storage-password: {{ .Values.tests.atpStorage.password }}
{{- end }}
