{{- if and .Values.tests.install .Values.atpReport.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-tests-atp-storage-secret
  labels:
    {{- include "kubernetes.labels" . | nindent 4 }}
type: Opaque
stringData:
  atp-storage-username: {{ .Values.atpReport.atpStorage.username }}
  atp-storage-password: {{ .Values.atpReport.atpStorage.password }}
{{- end }}
