{{- if .Values.patroni.powa.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: patroni
    name: powa-secret
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: powa-secret
data:
  password: {{ default "Pow@pASsWORD" .Values.patroni.powa.password | b64enc }}
type: Opaque
{{ end }}
