apiVersion: v1
kind: Secret
metadata:
  labels:
    app: patroni
    name: replicator-credentials
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: replicator-credentials
data:
  password: {{ .Values.replicatorPassword | b64enc }}
  username: {{ "replicator" | b64enc }}
type: Opaque
