{{- if and (.Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1") (eq .Values.PAAS_PLATFORM "KUBERNETES") -}}
{{ if and .Values.powaUI.install .Values.powaUI.ingress.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: powa-ui-httproute
  labels:
    {{ include "kubernetes.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ include "gateway.name" . }}
    namespace: {{ include "gateway.namespace" . }}
    port: 443
  hostnames: [{{ .Values.powaUI.ingress.host  | quote }}]
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: powa-ui
      port: 8080
{{- end }}
{{- end }}