{{ if .Values.patroni.applyPodDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: patroni-pdb
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: patroni
{{ end }}
