{{ if .Values.serviceAccount.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: patroni-core-operator
  labels:
    name: patroni-core
      {{ include "kubernetes.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - persistentvolumeclaims
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs:
  - get
  - list
  - patch
  - update
  - watch
  - delete
  - create
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list"]
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/scale
  - replicasets
  - statefulsets
  - statefulsets/scale
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
- apiGroups:
  - netcracker.com
  resources:
  - '*'
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
  - delete
{{ end }}
