{
 "title": "CloudSQL Postgres",
 "description": "Visualize OS metrics for Amazon RDS instance",
 "tags": [
  "cloud",
  "cloud-sql",
  "gcp",
  "postgres"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization, cluster)"
    }
   },
   {
    "name": "project_id",
    "label": "Project",
    "query": {
     "query": "label_values(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{cluster=~\"$cluster\"}, project_id)"
    }
   },
   {
    "name": "region",
    "label": "Region",
    "query": {
     "query": "label_values(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{project_id=\"$project_id\", cluster=~\"$cluster\"}, region)"
    }
   },
   {
    "name": "database_id",
    "label": "Database",
    "query": {
     "query": "label_values(stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{project_id=\"$project_id\", region=\"$region\", cluster=~\"$cluster\"}, database_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Current CPU utilization represented as a percentage of the reserved CPU that is currently in use.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_cpu_utilization{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"}",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "description": "Number of connections to the Cloud SQL PostgreSQL instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database_id) (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_postgresql_num_backends{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"})",
     "legendFormat": "connections"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Delta count of bytes sent through the network. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_network_received_bytes_count{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"}/60",
     "legendFormat": "Inbound"
    },
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_network_sent_bytes_count{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"}/60",
     "legendFormat": "OutBound"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "description": "Number of deadlocks detected for this database. Sampled every 60 seconds.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (database_id) (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_postgresql_deadlock_count{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"})",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "description": "The amount of available random access memory",
   "gridPos": { "h": 7, "w": 23, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_memory_quota{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"} - stackdriver_cloudsql_database_cloudsql_googleapis_com_database_memory_total_usage{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "description": "Delta count of data disk read IO operations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_disk_read_ops_count{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"}/60",
     "legendFormat": "Read"
    },
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_disk_write_ops_count{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"}/60",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Blocks read",
   "type": "timeseries",
   "description": "Number of disk blocks read by this database. ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "blocks/s" } },
   "yaxes": [
    { "format": "blocks/s" }
   ],
   "targets": [
    {
     "expr": "sum by (database_id) (stackdriver_cloudsql_database_cloudsql_googleapis_com_database_postgresql_blocks_read_count{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"})/60",
     "legendFormat": "Read"
    }
   ]
  },
  {
   "title": "Disk Utilization",
   "type": "timeseries",
   "description": "The fraction of the disk quota that is currently in use.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_disk_utilization{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"}",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Replica Lag",
   "type": "timeseries",
   "description": "Number of seconds the read replica is behind its primary (approximation).",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "stackdriver_cloudsql_database_cloudsql_googleapis_com_database_replication_replica_lag{project_id=\"$project_id\", region=\"$region\", database_id=\"$database_id\", cluster=~\"$cluster\"}",
     "legendFormat": "Lag"
    }
   ]
  }
 ]
}