{
 "title": "PostgreSQL Cluster Prometheus",
 "description": "Metrics for PostgreSQL Cluster",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Cloud", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(ma_status, cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Project",
    "query": {
     "query": "label_values(ma_status{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "container_name",
    "label": "PG Data Nodes",
    "query": {
     "query": "label_values(kube_pod_info{exported_namespace=~\"^$namespace$\", cluster=~\"$cluster\"}, exported_pod)"
    }
   },
   {
    "name": "inter",
    "label": "Sampling",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace_pods",
    "query": {
     "query": "label_values(kube_pod_info{exported_namespace=~\"^$namespace$\", cluster=~\"$cluster\"}, exported_pod)"
    }
   },
   {
    "name": "datname",
    "label": "Database Name",
    "query": {
     "query": "label_values(ma_pg_size_by_database{namespace=\"$namespace\", cluster=~\"$cluster\"},datname)"
    }
   },
   { "name": "limit", "label": "Top", "query": "5, 10, 20, 30, 40, 50" },
   { "name": "table_limit", "label": "Table Limit", "query": "10,50,100,500,1000,2000,5000" },
   {
    "name": "usename",
    "label": "Role Name",
    "query": {
     "query": "label_values(ma_pg_connection_by_role{namespace=\"$namespace\", cluster=~\"$cluster\"},usename)"
    }
   },
   {
    "name": "column",
    "label": "Top By Column",
    "query": "calls, max_time, min_time, mean_time, total_time"
   },
   {
    "name": "top_tables_by_size",
    "query": {
     "query": "query_result(topk($limit, sum by (relid, datname, relname) (last_over_time(ma_pg_table_size_by_db{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}[$__range:]))))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "PostgreSQL Cluster Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by () (ma_pg_patroni_cluster_status{namespace=\"$namespace\", cluster=~\"$cluster\"} or ma_pg_metrics_running{namespace=\"$namespace\", cluster=~\"$cluster\", pg_node='External'})",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM /pg.$cluster_name.cluster.status/ WHERE namespace='$namespace' and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PostgreSQL Cluster Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ma_pg_patroni_cluster_active{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"value\") FROM /pg.$cluster_name.cluster.status/ WHERE namespace='$namespace' and $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "description": "Postgres server version",
   "gridPos": { "h": 7, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "postgres_version{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Nodes (1 = OK)",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$4",
     "expr": "ma_pg_metrics_running{namespace=\"$namespace\", cluster=~\"$cluster\"}",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{pg_node}}",
     "query": "SELECT mean(value) FROM /pg.$cluster_name.nodes.node.*.pg_metrics.running/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Metric Sources (1 = OK)",
   "type": "state-timeline",
   "description": "Shows whether metric sources work. If the value is greater than 1, then the source returns error. If the value is zero, then the source is down.",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_service_name",
     "expr": "ma_status{namespace=\"$namespace\", cluster=~\"$cluster\"} + 1",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{ service_name }}",
     "query": "select 1 - ( max(\"value\") / 14 - max(\"value\") % 14 / 14)  from /ma.status/  WHERE namespace='$namespace' and $timeFilter group by service_name, time($interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Patroni Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Patroni Members Status (1 = OK)",
     "type": "state-timeline",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_patroni_patroni_status{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "SELECT mean(value) FROM /pg.$cluster_name.nodes.node.*.patroni_status/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Smoke test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Smoke Test",
     "type": "timeseries",
     "description": "Shows whether the cluster serves RW requests (select, insert, update, delete) through the endpoint.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ma_pg_endpoints_cluster_smoketest_check{namespace=\"$namespace\", cluster=~\"$cluster\"} ",
       "legendFormat": "{{action}}"
      }
     ]
    },
    {
     "title": "Smoke Tests Timings",
     "type": "timeseries",
     "description": "Shows the execution time for a **single** RW request (select, insert, update, delete) through the endpoint.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "delete",
       "expr": "ma_pg_endpoints_cluster_smoketest_time_ms{namespace=\"$namespace\", cluster=~\"$cluster\"} ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{action}}",
       "query": "SELECT mean(\"value\") FROM /pg.$cluster_name.endpoints.cluster.smoketest.delete.*time_ms$/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Endpoint Cluster Status (1 = Running)",
     "type": "timeseries",
     "description": "Shows whether monitoring is able to connect to PostgreSQL through the endpoint.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "ma_pg_endpoints_cluster_running{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Leader",
       "query": "SELECT mean(\"value\") FROM /pg.$cluster_name.endpoints.cluster.running/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU Usage: $namespace_pods",
     "type": "timeseries",
     "description": "Shows CPU consumption in PostgreSQL pods based on metrics collected from docker. This section does not use collector metrics.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 11 },
     "repeat": "namespace_pods",
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "usage",
       "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\", container!=\"POD\", namespace=\"$namespace\", pod=\"$namespace_pods\", cluster=~\"$cluster\"}[2m])) by (pod_name, container)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "container" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "usage",
       "measurement": "cpu/usage_rate",
       "query": "SELECT mean(value) FROM \"cpu/usage_rate\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND \"container_name\" = '$container_name' AND $timeFilter GROUP BY time($interval), pod_name fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "pod_container" },
        { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
       ]
      },
      {
       "expr": "kube_pod_container_resource_limits_cpu_cores{exported_namespace=\"$namespace\", exported_pod=\"$namespace_pods\", cluster=~\"$cluster\"}",
       "legendFormat": "limit"
      }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Usage: $namespace_pods",
     "type": "timeseries",
     "description": "Shows memory consumption in PostgreSQL pods based on metrics collected from docker. This section does not use collector metrics.",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 12 },
     "repeat": "namespace_pods",
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "usage",
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$namespace_pods\", image!=\"\", container!=\"POD\", cluster=~\"$cluster\"}) by (pod_name)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Working Set",
       "measurement": "memory/usage",
       "query": "SELECT max(\"value\") FROM \"memory/usage\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND  \"container_name\" = '$container_name'  AND $timeFilter GROUP BY time($interval), pod_name  fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "pod_container" },
        { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
       ]
      },
      {
       "alias": "working set",
       "expr": "sum(container_spec_memory_limit_bytes{image!=\"\", namespace=\"$namespace\", pod=\"$namespace_pods\", cluster=~\"$cluster\"}) by (pod_name)",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "container_name" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "limits",
       "measurement": "memory/usage",
       "query": "SELECT max(\"value\") FROM \"memory/working_set\" WHERE \"type\" = 'pod_container' AND \"namespace_name\" = '$namespace' AND  \"container_name\" = '$container_name' AND $timeFilter GROUP BY time($interval), pod_name  fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "sum"
         }
        ]
       ],
       "tags": [
        { "key": "type", "operator": "=", "value": "pod_container" },
        { "condition": "AND", "key": "namespace_name", "operator": "=~", "value": "/$namespace$/" },
        { "condition": "AND", "key": "pod_name", "operator": "=~", "value": "/$podname$/" }
       ]
      },
      {
       "expr": "sum(container_memory_working_set_bytes{namespace=\"$namespace\", pod=\"$namespace_pods\", image!=\"\", container!=\"POD\", cluster=~\"$cluster\"}) by (pod_name)",
       "legendFormat": "Memory Usage"
      },
      {
       "expr": "sum(container_memory_cache{namespace=\"$namespace\", pod=\"$namespace_pods\", image!=\"\", container!=\"POD\", cluster=~\"$cluster\"}) by (pod_name)",
       "legendFormat": "Memory Cache"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Current Connections",
     "type": "timeseries",
     "description": "Shows the number of connections to PostgreSQL pods.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_metrics_current_connections{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "SELECT mean(\"value\") FROM /pg\\.$cluster_name\\.nodes\\.node\\d+\\..*\\.current_connections/ WHERE namespace='$namespace' and $timeFilter group by service_name, time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "ma_pg_metrics_postgres_max_connections{namespace=\"$namespace\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Replication Connections",
     "type": "timeseries",
     "description": "Shows the number of replication connections to PostgreSQL pods.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_metrics_replication_connections{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "SELECT mean(value) FROM /pg\\.$cluster_name\\.nodes\\.node\\d+\\..*pg_metrics\\.replication_connections/ WHERE namespace='$namespace' and $timeFilter group by service_name, time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TPS",
     "type": "timeseries",
     "description": "Estimated value for transactions per second. Calculated as transaction amount for last 30 seconds divided by 30.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "sum(irate(ma_pg_metrics_xact_sum{namespace=\"$namespace\", cluster=~\"$cluster\"}[$__rate_interval]))",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "SELECT non_negative_derivative(mean(\"value\"), 1s) FROM /pg\\.$cluster_name\\.nodes\\.node\\d+.*\\.pg_metrics\\.xact_sum/ WHERE namespace='$namespace' and $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk Usage Percentage",
     "type": "timeseries",
     "description": "Shows disk usage for PostgreSQL pods.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_patroni_metrics_df_pcent{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "SELECT /value/ FROM /pg\\.$cluster_name\\.nodes\\.node\\d+.*\\.metrics\\.df\\.pcent/ WHERE namespace='$namespace' and $timeFilter group by service_name",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Disk Usage",
     "type": "timeseries",
     "description": "Shows usage by well-known consumers, such as pg_xlog or base directories.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "repeat": "short_container_name",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$7",
       "expr": "ma_pg_patroni_metrics_du_base{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "SELECT /value/ FROM /pg\\.$cluster_name\\.nodes\\.$short_container_name\\.metrics\\.du\\.(.?)/ WHERE namespace='$namespace' and $timeFilter group by service_name",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Data handing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "DataBases Count",
     "type": "timeseries",
     "description": "Shows current DB count in PostgreSQL pods.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_metrics_db_count{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "SELECT mean(\"value\") FROM /pg\\.$cluster_name\\.nodes\\.node\\d+.*\\.pg_metrics\\.db_count/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "XLOG Location",
     "type": "timeseries",
     "description": "Shows current XLOG location. This value is correlated with the transaction count, or the number of changes made to the database.\nThe master and replica should have the same value, with a short period while the replica catches up to the master. \nThe value on the replica can be slightly less than the master's, but should increase over time.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_metrics_xlog_location{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "select /value/ from /pg\\.$cluster_name\\.nodes\\.node\\d+.*\\.pg_metrics\\.xlog_location/ where namespace = '$namespace' and $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Locks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Locks",
     "type": "timeseries",
     "description": "Number of locks from pg_locks view.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_metrics_locks{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "SELECT mean(\"value\") FROM /pg\\.$cluster_name\\.nodes\\.node\\d+.*\\.pg_metrics\\.locks$/ WHERE namespace='$namespace' and $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Locks not granted",
     "type": "timeseries",
     "description": "Number of locks from pg_locks view that are not granted.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_metrics_locks_not_granted{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{pg_node}}",
       "query": "SELECT mean(\"value\") FROM /pg\\.$cluster_name\\.nodes\\.node\\d+.*\\.pg_metrics\\.locks_not_granted/ WHERE namespace='$namespace' and $timeFilter GROUP BY time($interval)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Master Smoke Test",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Smoke Test",
     "type": "timeseries",
     "description": "This like the \"Smoke test\" section, with one difference - this section executes smoketests directly on the master pod.\nThe difference in execution allows distinguishing between cases of master unavailability and endpoint failure.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "delete",
       "expr": "ma_pg_endpoints_cluster_smoketest_check{namespace=\"$namespace\", cluster=~\"$cluster\"} ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{action}}",
       "query": "SELECT mean(value) FROM /pg.$cluster_name.nodes.*.smoketest.delete.*check$/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Smoke Tests Timings",
     "type": "timeseries",
     "description": "This like the \"Smoke test\" section, with one difference - this section executes smoketests directly on the master pod.\n The difference in execution allows distinguishing between cases of master unavailability and endpoint failure.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$6",
       "expr": "ma_pg_endpoints_cluster_smoketest_time_ms{namespace=\"$namespace\", cluster=~\"$cluster\"} ",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{action}}",
       "query": "SELECT mean(value) FROM/pg.$cluster_name.nodes.*.smoketest.delete.*time_ms$/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backup Last Version Size",
     "type": "timeseries",
     "description": "Shows the size of the last backup.",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "ma_storage_last_metrics_size{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Size",
       "query": "SELECT last(value) FROM \"ma.storage.last.metrics.size\" WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Storage Size/Free Space",
     "type": "timeseries",
     "description": "Shows the space occupied by backups and the remaining amount of space. \nNot all storage supports total size, so \"Total Volume Space\" metrics can be zeroed.",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Space Used",
       "expr": "ma_storage_total_space{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Total Space",
       "query": "SELECT last(value) FROM /storage\\.size/ WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Total Volume Space",
       "expr": "ma_storage_size{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Storage Size",
       "query": "SELECT last(value) FROM /storage\\.total_space/ WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time Spent on Backup",
     "type": "timeseries",
     "description": "Shows time spent on last backup.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "Time Spent on Each Backup",
       "expr": "ma_storage_lastSuccessful_metrics_spent_time{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Time Spent",
       "query": "SELECT mean(value) FROM /storage\\.lastSuccessful\\.metrics\\.spent_time/ WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter  GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backup Activity Status",
     "type": "timeseries",
     "description": "Shows the changes of activity status on the chart.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "Time Spent on Each Backup",
       "expr": "ma_backup_is_in_progress{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Time in progress",
       "query": "SELECT last(\"value\") FROM \"ma.backup_is_in_progress\" WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Last Backup Status",
     "type": "stat",
     "description": "Backup status shows the state of the backup daemon. The backup status can be one of following:\n \n* OK - There is at least one successful backup, and the latest backup is successful.\n* WARNING - There are no successful backups, or the last backup failed.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ma_status{namespace=\"$namespace\", service_name=\"postgres-backup-daemon\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(value) FROM /status/ WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Storage Type",
     "type": "stat",
     "description": "Shows the backup storage type.",
     "gridPos": { "h": 5, "w": 5, "x": 4, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ma.storage.type",
       "query": "SELECT last(value) FROM \"ma.storage.type\" WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      },
      {}
     ]
    },
    {
     "title": "Backup Activity Status",
     "type": "stat",
     "description": "Shows the current activity status of the backup daemon. The activity status can be one of following:\n* Not Active - There is no running backup process.\n* In Progress - The backup process is running.",
     "gridPos": { "h": 5, "w": 5, "x": 9, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ma_backup_is_in_progress{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ma.backup_is_in_progress",
       "query": "SELECT last(\"value\") FROM \"ma.backup_is_in_progress\" WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time of Last Successful Backup",
     "type": "stat",
     "description": "Shows the period of time when the last successful backup process was ended.",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ma_storage_lastSuccessful_end_timestamp_ago{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ma.storage.last.metrics.end_timestamp",
       "query": "SELECT last(\"value\") FROM \"ma.storage.lastSuccessful.end_timestamp_ago\" WHERE namespace='$namespace' and $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Time of Last Backup",
     "type": "stat",
     "description": "Shows the period of time when the last backup process was ended.",
     "gridPos": { "h": 5, "w": 5, "x": 19, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ma_storage_last_end_timestamp_ago{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ma.storage.last.metrics.end_timestamp",
       "query": "SELECT last(\"value\") FROM \"ma.storage.last.end_timestamp_ago\" WHERE namespace='$namespace' and $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Outdated Backup Count",
     "type": "stat",
     "description": "Shows the number of backups that will be evicted next time.",
     "gridPos": { "h": 5, "w": 4, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ma_storage_outdated_backup_count{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ma.storage.foul_backup_count",
       "query": "SELECT last(\"value\") FROM \"ma.storage.outdated_backup_count\" WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter  GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Next Backup",
     "type": "stat",
     "description": "Shows the time when backup and eviction will be started.",
     "gridPos": { "h": 5, "w": 5, "x": 4, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ma_backup_time_until_next_backup{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ma.storage.dump_count",
       "query": "SELECT last(\"value\") FROM \"ma.backup.time_until_next_backup\" WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Successful Backup Versions Count",
     "type": "stat",
     "description": "Shows the amount of successful backups.",
     "gridPos": { "h": 5, "w": 5, "x": 9, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ma_storage_successful_dump_count{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ma.storage.dump_count",
       "query": "SELECT last(\"value\") FROM \"ma.storage.successful_dump_count\" WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Backup Versions Count",
     "type": "stat",
     "description": "Shows the amount of available backups.",
     "gridPos": { "h": 5, "w": 5, "x": 14, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "ma_storage_dump_count{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "ma.storage.dump_count",
       "query": "SELECT last(\"value\") FROM \"ma.storage.dump_count\" WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Archive",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Archive mode",
     "type": "stat",
     "description": "If archive mode is on, then the WAL archive is enabled. Otherwise, the WAL archive is disabled.",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "ma_pg_patroni_pg_metrics_archive_mode_prom{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT last(\"value\") FROM /pg.$cluster_name.*.archive.mode/ WHERE namespace='$namespace' and $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Archive Lag, s",
     "type": "timeseries",
     "description": "Shows the time in seconds since the last WAL file was archived. If rotation is disabled, and load on server is close to zero, this value can reach thousand of seconds.",
     "gridPos": { "h": 7, "w": 6, "x": 4, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$6",
       "expr": "ma_pg_patroni_pg_metrics_archive_delay{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "delay",
       "query": "SELECT mean(value) FROM/pg.$cluster_name.nodes.*.archive.delay$/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Failed to archive",
     "type": "timeseries",
     "description": "Shows the amount of failed attempts to flush WAL files to archive. If this value is greater than 0, the system checks whether backup daemon is running and has enough space to store files.",
     "gridPos": { "h": 7, "w": 7, "x": 10, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$6",
       "expr": "ma_pg_patroni_pg_metrics_archive_failed_count{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "count",
       "query": "SELECT mean(value) FROM/pg.$cluster_name.nodes.*.archive.failed_count/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Storage Size/Free Space",
     "type": "timeseries",
     "description": "Shows the space occupied by WAL archive and the remaining amount of space. Not all storage supports total size, so \"Total Volume Space\" metrics can be zeroed.",
     "gridPos": { "h": 7, "w": 7, "x": 17, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Space Used",
       "expr": "ma_storage_total_space{exported_namespace=\"$namespace\", service_name=\"postgres-backup-daemon\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "Total Space",
       "query": "SELECT last(value) FROM /storage\\.archive_size/ WHERE namespace='$namespace' and service_name='postgres-backup-daemon' and $timeFilter GROUP BY time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Replication state",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Sent lag",
     "type": "timeseries",
     "description": "Shows the difference between the current XLOG location and the data that was sent to recipient.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$7",
       "expr": "ma_pg_patroni_replication_lag{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ hostname }}",
       "query": "SELECT mean(value) FROM /pg\\.$cluster_name\\..*\\.pg_metrics\\.replication\\.(.*).sent_lag/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Sent/Replay lag",
     "type": "timeseries",
     "description": "Shows the difference between the sent XLOG location and applied to the recipient XLOG location.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "$7",
       "expr": "ma_pg_patroni_replication_state_sent_replay_lag{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ hostname }}",
       "query": "SELECT mean(value) FROM /pg\\.$cluster_name\\..*\\.pg_metrics\\.replication\\.(.*).sent_replay_lag/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Collector status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Collector duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "alias": "duration",
       "expr": "ma_collector_duration{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ host }}",
       "query": "SELECT value FROM /collector.duration/ WHERE namespace='$namespace' and $timeFilter fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Database Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Size by database",
     "type": "timeseries",
     "description": "This graph shows size for all of the logical databases in PostgreSQL cluster.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_size_by_database{namespace=\"$namespace\", datname=~\"$datname\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ datname }}",
       "query": "SELECT mean(\"value\") / 1024 / 1024 FROM /pg.common.size_by_database.*/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of Tables",
     "type": "timeseries",
     "description": "This graph shows number of table in each of the logical databases.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "expr": "count by (datname) (ma_pg_table_size_by_db{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"})",
       "legendFormat": "{{ datname }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Connection Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Overall connection statistic",
     "type": "timeseries",
     "description": "Shows how many connections are in use right now. It shows max connections, used connections, reserved for regular, and superuser.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_connection_count_stat_max_connections{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "stat max connections",
       "query": "SELECT mean(\"value\") FROM /pg.common.connection_count_stat.*/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "expr": "ma_pg_connection_count_stat_reserved_for_reg_users{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "legendFormat": "reserved for reg_users"
      },
      {
       "expr": "ma_pg_connection_count_stat_reserved_for_superuser{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "legendFormat": "reserved for superuser"
      },
      {
       "expr": "ma_pg_connection_count_stat_used{namespace=\"$namespace\", cluster=~\"$cluster\"}",
       "legendFormat": "used"
      }
     ]
    },
    {
     "title": "Connection by database",
     "type": "timeseries",
     "description": "Shows the number of connections per database.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_connection_by_database{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ datname }}",
       "query": "SELECT mean(\"value\") FROM /pg.common.connection_by_database.*/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Connection by role",
     "type": "timeseries",
     "description": "Shows the number of connections per role.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_connection_by_role{namespace=\"$namespace\", usename=~\"$usename\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ usename }}",
       "query": "SELECT mean(\"value\") FROM /pg.common.connection_by_database.*/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Not idle connections by Database",
     "type": "timeseries",
     "description": "Shows the number of not idle connections per database.",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "alias": "$4",
       "expr": "ma_pg_count_not_idle{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}",
       "groupBy": [
        { "params": [ "$interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "legendFormat": "{{ datname }}",
       "query": "SELECT mean(\"value\") FROM /pg.common.count_not_idle.*/ WHERE namespace='$namespace' and $timeFilter group by time($interval) fill(previous)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Number of Active Connections by Role",
     "type": "table",
     "description": "This table shows number of Active Connections in current moment by role. Also shows Connection Limits that is set during Role create. Also, shows not idle connection by role.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "last_over_time(ma_pg_connection_by_role_with_limit{namespace=\"$namespace\", usename=~\"$usename\", cluster=~\"$cluster\"}[$__range:])",
       "groupBy": [
        { "params": [ "queryid" ], "type": "tag" }
       ],
       "legendFormat": "Connections",
       "measurement": "ma.pg.common.queries_stat",
       "query": "SELECT top(\"$column\", $limit) as \"$column\", \"short_query\", \"datname\", \"mean_time\", \"queryid\" FROM (SELECT LAST(\"queryid_val\"), * FROM \"ma.pg.common.queries_stat\" WHERE $timeFilter and (\"datname\" = '$datname' OR 'All' = '$datname' ) and \"namespace\" = '$namespace'  GROUP BY \"queryid\" ORDER BY DESC LIMIT 1) ORDER BY DESC",
       "select": [
        [
         { "params": [ "mean_time" ], "type": "field" },
         { "params": [ "30" ], "type": "top" }
        ],
        [
         { "params": [ "calls" ], "type": "field" }
        ],
        [
         { "params": [ "short_query" ], "type": "field" }
        ],
        [
         { "params": [ "datname" ], "type": "field" }
        ],
        [
         { "params": [ "total_time" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  { "title": "Temp File Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Temporary Files Size By Query",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "ma_pg_temp_file_size_by_query{namespace=~\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temporary File Count By Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "ma_pg_temp_file_count_by_db{datname=~\"$datname\", namespace=\"$namespace\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Temp Writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "ma_pg_active_temp_writes{namespace=\"$namespace\", datname=\"$datname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Temporary Files Size By Database",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "ma_pg_temp_file_size_by_db{namespace=~\"test-perm7|$namespace\", datname=~\"$datname\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tables Statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "TOP $limit tables by size",
     "type": "table",
     "description": "The table shows TOP tables filtered by the selected database name.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum by (relid, relname, datname, selector) (ma_pg_table_size_by_db{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\", relname=~\"$top_tables_by_size\"})",
       "groupBy": [
        { "params": [ "queryid" ], "type": "tag" }
       ],
       "measurement": "ma.pg.common.queries_stat",
       "query": "SELECT top(\"$column\", $limit) as \"$column\", \"short_query\", \"datname\", \"mean_time\", \"queryid\" FROM (SELECT LAST(\"queryid_val\"), * FROM \"ma.pg.common.queries_stat\" WHERE $timeFilter and (\"datname\" = '$datname' OR 'All' = '$datname' ) and \"namespace\" = '$namespace'  GROUP BY \"queryid\" ORDER BY DESC LIMIT 1) ORDER BY DESC",
       "select": [
        [
         { "params": [ "mean_time" ], "type": "field" },
         { "params": [ "30" ], "type": "top" }
        ],
        [
         { "params": [ "calls" ], "type": "field" }
        ],
        [
         { "params": [ "short_query" ], "type": "field" }
        ],
        [
         { "params": [ "datname" ], "type": "field" }
        ],
        [
         { "params": [ "total_time" ], "type": "field" }
        ]
       ]
      },
      {
       "expr": "sum by (relid, relname, datname, selector) (ma_pg_tuples_by_db{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\", relname=~\"$top_tables_by_size\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (relid, relname, datname, selector) (ma_pg_tot_size_by_db{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\", relname=~\"$top_tables_by_size\"})",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum by (relid, relname, datname, selector) (ma_pg_idx_size_by_db{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\", relname=~\"$top_tables_by_size\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Size by tables",
     "type": "timeseries",
     "description": "This Graph Shows size of the each table in all of the databases",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "targets": [
      {
       "expr": "topk($table_limit, sort_desc(ma_pg_table_size_by_db{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}))",
       "legendFormat": "{{ datname }}/{{ relname }}"
      }
     ]
    },
    {
     "title": "Estimated Number of Rows per Table",
     "type": "timeseries",
     "description": "This graphs shows estimated number of rows in all of the tables, using `pg_stat_all_tables` system view.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "topk($table_limit, sort_desc(ma_pg_tuples_by_db{namespace=\"$namespace\", datname=~\"$datname\", cluster=~\"$cluster\"}))",
       "legendFormat": "{{datname}}/{{ relname }}"
      }
     ]
    },
    {
     "title": "TOP $limit queries by $column",
     "type": "table",
     "description": "The table shows TOP queries filtered by the selected column and database name.  For queries statistics `pg_stat_statements`  view used. More info about columns could be find in official docs.\n\nAlso, it is possible to reset the statistics, by calling `pg_stat_statements_reset()` function.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
     "targets": [
      {
       "expr": "last_over_time(topk($limit,sort_desc(ma_pg_queries_stat{namespace=\"$namespace\", metric_name=\"$column\", datname=~\"$datname\", cluster=~\"$cluster\"}))[$__range:])",
       "groupBy": [
        { "params": [ "queryid" ], "type": "tag" }
       ],
       "measurement": "ma.pg.common.queries_stat",
       "query": "SELECT top(\"$column\", $limit) as \"$column\", \"short_query\", \"datname\", \"mean_time\", \"queryid\" FROM (SELECT LAST(\"queryid_val\"), * FROM \"ma.pg.common.queries_stat\" WHERE $timeFilter and (\"datname\" = '$datname' OR 'All' = '$datname' ) and \"namespace\" = '$namespace'  GROUP BY \"queryid\" ORDER BY DESC LIMIT 1) ORDER BY DESC",
       "select": [
        [
         { "params": [ "mean_time" ], "type": "field" },
         { "params": [ "30" ], "type": "top" }
        ],
        [
         { "params": [ "calls" ], "type": "field" }
        ],
        [
         { "params": [ "short_query" ], "type": "field" }
        ],
        [
         { "params": [ "datname" ], "type": "field" }
        ],
        [
         { "params": [ "total_time" ], "type": "field" }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "DBaaS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "DbaaS Mappings",
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "sum by (datname, db_namespace, microservice, tenant_id) (last_over_time(ma_pg_dbaas{namespace=\"$namespace\", cluster=~\"$cluster\"}[$__range:]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}