{{ if .Values.patroni.applyPodDisruptionBudget }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: patroni-pdb
  labels:
    name: patroni-pdb
      {{ include "kubernetes.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: patroni
{{ end }}
