{{ if .Values.powaUI.install }}
{{- if .Values.powaUI.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    name: powa-ui-ingress
      {{ include "kubernetes.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.tls.enabled }}
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
    nginx.ingress.kubernetes.io/proxy-ssl-verify: 'on'
    nginx.ingress.kubernetes.io/proxy-ssl-name: '{{ printf "powa-ui.%s" .Release.Namespace }}'
    nginx.ingress.kubernetes.io/proxy-ssl-secret: '{{ printf "%s/%s" .Release.Namespace (include "postgres.certServicesSecret" .) }}'
  {{- end }}
  name: powa-ui-ingress
spec:
  {{- if .Values.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.powaUI.ingress.host }}
  {{- end }}
  rules:
    - host: {{ .Values.powaUI.ingress.host }}
      http:
        paths:
          - backend:
              service:
                name: powa-ui
                port:
                  name: web
            path: /
            pathType: ImplementationSpecific
{{ end }}
{{ end }}
