{{ if .Values.serviceAccount.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: postgres-operator
  labels:
    name: postgres-operator
      {{ include "kubernetes.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
roleRef:
  kind: Role
  name: postgres-operator
  apiGroup: rbac.authorization.k8s.io
{{ end }}
