{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  labels:
    name: {{ .Values.serviceAccount.name }}
      {{ include "kubernetes.labels" . | nindent 4 }}
{{- end }}
