# Copyright 2024-2025 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if .Values.externalDataBase }}
{{- if eq .Values.externalDataBase.type "rds" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres-backup-daemon
    name: postgres-backup-daemon
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: aws-credentials
data:
  access_key: {{ default "#" .Values.externalDataBase.secretAccessKey | b64enc }}
  key_id: {{ default "#" .Values.externalDataBase.accessKeyId | b64enc }}
type: Opaque
{{ end }}
{{ end }}