{{- if .Values.externalDataBase }}
{{- if eq .Values.externalDataBase.type "rds" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres-backup-daemon
    name: postgres-backup-daemon
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: aws-credentials
data:
  access_key: {{ default "#" .Values.externalDataBase.secretAccessKey | b64enc }}
  key_id: {{ default "#" .Values.externalDataBase.accessKeyId | b64enc }}
type: Opaque
{{ end }}
{{ end }}
