{{ if .Values.metricCollector.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: monitoring-collector
    name: monitoring-collector
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: influx-db-admin-credentials
data:
  {{ if .Values.metricCollector.influxDb }}
  password: {{ default "admin" .Values.metricCollector.influxDb.password | b64enc }}
  username: {{ default "admin" .Values.metricCollector.influxDb.user | b64enc }}
{{ else }}
  password: ""
  username: ""
{{ end }}
type: Opaque
{{ end }}
