{{- if .Values.replicationController.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: logical-replication-controller
    name: logical-replication-controller-creds
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: logical-replication-controller-creds
data:
  username: {{ default "replicator" .Values.replicationController.apiUser | b64enc }}
  password: {{ default "paSsW0rdForReplicat!oN" .Values.replicationController.apiPassword | b64enc }}
type: Opaque
{{ end }}
