{{- if (eq (include "monitoring.install" .) "true") }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: monitoring-collector
    name: monitoring-collector
    {{ include "kubernetes.labels" . | nindent 4 }}
  name: monitoring-credentials
data:
  username: {{ "monitoring-user" | b64enc }}
  password: {{ .Values.metricCollector.userPassword | b64enc }}
type: Opaque
{{- end }}