{{- if .Values.connectionPooler.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: patroni
    name: patroni
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: pgbouncer-secret
data:
  userlist.txt: {{ printf "\"%s\" \"%s\"" (default "pgbouncer" .Values.connectionPooler.username) (default "pgbouncer" .Values.connectionPooler.password) | b64enc }}
type: Opaque
{{ end }}
