{{- if eq .Values.backupDaemon.storage.type "s3" }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: postgres-backup-daemon
    name: postgres-backup-daemon
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: s3-storage-credentials
data:
  access_key: {{ .Values.backupDaemon.s3Storage.secretAccessKey | b64enc }}
  key_id: {{ .Values.backupDaemon.s3Storage.accessKeyId | b64enc }}
type: Opaque
{{ end }}
