# Copyright 2024-2025 NetCracker Technology Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

{{- if and (eq (include "monitoring.install" .) "true") (.Values.metricCollector.prometheusMonitoring) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-service-monitor
  labels:
    name: postgres-service-monitor
    k8s-app: postgres-service-monitor
    app.kubernetes.io/name: postgres-service-monitor
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: platform-monitoring
    app.kubernetes.io/managed-by: platform-monitoring-operator
spec:
  endpoints:
  - interval: {{ .Values.metricCollector.collectionInterval }}s
    scrapeTimeout: {{ default "20" .Values.metricCollector.scrapeTimeout }}s
    port: prometheus-port
    scheme: http
  jobLabel: k8s-app
  namespaceSelector:
    {{ if  .Release.Namespace }}
    matchNames:
      - {{ .Release.Namespace }}
    {{ else }}
    matchNames:
      - {{ default "postgres-service" .Values.NAMESPACE }}
    {{ end }}
  selector:
    matchLabels:
      app: monitoring-collector
{{ end }}
