{
 "title": "Amazon Aurora Metrics",
 "description": "Visualize OS metrics for Amazon RDS instance",
 "tags": [
  "cloud",
  "aws",
  "rds",
  "postgres"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(aws_rds_database_connections_sum, cluster)"
    }
   },
   {
    "name": "rds_cluster",
    "label": "DB Cluster",
    "query": {
     "query": "label_values(aws_rds_volume_bytes_used_average{cluster=\"$cluster\"}, dbcluster_identifier)"
    }
   },
   {
    "name": "rds_instance",
    "label": "DB Instance",
    "query": {
     "query": "label_values(aws_rds_database_connections_sum{cluster=\"$cluster\"}, dbinstance_identifier)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "The percentage of CPU used by an Aurora DB instance",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "aws_rds_cpuutilization_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Database connections",
   "type": "timeseries",
   "description": "The number of client network connections to the database instance",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_rds_database_connections_sum{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "{{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "The amount of network throughput received from clients by each instance in the Aurora PostgreSQL DB cluster and the amount of network throughput sent to clients by each instance in the Aurora DB cluster",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "aws_rds_network_receive_throughput_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Inbound"
    },
    {
     "expr": "aws_rds_network_transmit_throughput_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "OutBound"
    }
   ]
  },
  {
   "title": "Deadlocks",
   "type": "timeseries",
   "description": "The average number of deadlocks in the database per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "aws_rds_deadlocks_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Deadlocks"
    }
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Freeable Memory",
   "type": "timeseries",
   "description": "The amount of available random access memory",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_rds_freeable_memory_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "timeseries",
   "description": "The amount of swap space used",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "aws_rds_swap_usage_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Used"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "description": "The average number of disk I/O operations per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_iops_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "aws_rds_write_iops_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "timeseries",
   "description": "The average amount of time taken per disk I/O operation",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_latency_maximum{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Read {{dbinstance_identifier}}"
    },
    {
     "expr": "aws_rds_write_latency_maximum{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Write {{dbinstance_identifier}}"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "description": "The number of outstanding read/write requests waiting to access the disk",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "aws_rds_disk_queue_depth_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Outstanding IO Requests"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "The average number of bytes read/write from disk per second",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "aws_rds_read_throughput_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "aws_rds_write_throughput_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Free Local Storage",
   "type": "timeseries",
   "description": "The amount of Local Storage Available.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "aws_rds_free_local_storage_average{cluster=\"${cluster}\", dbinstance_identifier=~\"${rds_instance}\"}",
     "legendFormat": "Free Local Storage"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Replica Lag Minimum/Maximum",
     "type": "graph",
     "description": "The minimum/maximum amount of lag between the primary instance and each Aurora DB instance in the DB cluster",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "aws_rds_aurora_replica_lag_minimum_average{cluster=\"${cluster}\", dbinstance_identifier=\"$rds_instance\"}",
       "legendFormat": "Min {{dbinstance_identifier}}"
      },
      {
       "expr": "aws_rds_aurora_replica_lag_maximum_average{cluster=\"${cluster}\", dbinstance_identifier=\"$rds_instance\"}",
       "legendFormat": "Max {{dbinstance_identifier}}"
      }
     ]
    },
    {
     "title": "Aurora Replica Lag",
     "type": "graph",
     "description": "For an Aurora replica, the amount of lag when replicating updates from the primary instance",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "aws_rds_aurora_replica_lag_average{cluster=\"${cluster}\", dbinstance_identifier=\"$rds_instance\"}",
       "legendFormat": "{{dbinstance_identifier}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volume Bytes Used",
     "type": "graph",
     "description": "The amount of storage used by Aurora DB instance",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "aws_rds_volume_bytes_used_average{cluster=\"${cluster}\", dbcluster_identifier=\"${rds_cluster}\"}",
       "legendFormat": "Volume Used"
      }
     ]
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Backup Jobs",
     "type": "table",
     "description": "The number of backup jobs in different states",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "aws_backup_number_of_backup_jobs_running_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Running Jobs"
      },
      {
       "expr": "aws_backup_number_of_backup_jobs_created_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Created Jobs"
      },
      {
       "expr": "aws_backup_number_of_backup_jobs_completed_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Completed Jobs"
      },
      {
       "expr": "aws_backup_number_of_backup_jobs_aborted_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Aborted Jobs"
      },
      {
       "expr": "aws_backup_number_of_backup_jobs_pending_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Pending Jobs"
      },
      {
       "expr": "aws_backup_number_of_backup_jobs_failed_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Failed Jobs"
      },
      {
       "expr": "aws_backup_number_of_backup_jobs_expired_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Expired Jobs"
      }
     ]
    },
    {
     "title": "Restore Jobs",
     "type": "table",
     "description": "The number of restore jobs in different states",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "aws_backup_number_of_restore_jobs_pending_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}"
      },
      {
       "expr": "aws_backup_number_of_restore_jobs_running_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Running Jobs"
      },
      {
       "expr": "aws_backup_number_of_restore_jobs_completed_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Completed Jobs"
      },
      {
       "expr": "aws_backup_number_of_restore_jobs_failed_average{cluster=\"${cluster}\", resource_type=\"Aurora\"}",
       "legendFormat": "Failed Jobs"
      }
     ]
    }
   ]
  }
 ]
}