{
 "title": "Postgres Azure Metrics",
 "description": "Visualize OS metrics for Amazon RDS instance",
 "tags": [
  "cloud",
  "azure",
  "azure-postgresql",
  "postgres"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "DB Cluster",
    "query": {
     "query": "label_values(dbcluster_identifier)"
    }
   },
   {
    "name": "instance",
    "label": "DB Instance",
    "query": {
     "query": "label_values(postgresql_cpu_usage_millicores{cluster=~\"$cluster\"}, instance_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Instance Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "DB alive",
   "type": "timeseries",
   "description": "Indicates if the database is up or not",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "targets": [
    {
     "expr": "postgresql_is_db_alive{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Is db alive"
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "timeseries",
   "description": "Percentage of CPU in use",
   "gridPos": { "h": 7, "w": 9, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "postgresql_cpu_usage_millicores{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "description": "Amount of incoming/outgoing network traffic",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "postgresql_network_bytes_ingress{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Inbound"
    },
    {
     "expr": "postgresql_network_bytes_egress{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "OutBound"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Memory Used",
   "type": "timeseries",
   "description": "Percentage of memory in use",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "postgresql_memory_percent{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Memory Used"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Operations",
   "type": "timeseries",
   "description": "Number of data disk I/O read/write operations per second",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "postgresql_read_iops{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "postgresql_write_iops{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "timeseries",
   "description": "Bytes read/write per second from disk",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "postgresql_read_throughput{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Read"
    },
    {
     "expr": "postgresql_write_throughput{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "timeseries",
   "description": "Number of outstanding I/O operations to the data disk",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "postgresql_disk_queue_depth{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Outstanding IO Requests"
    }
   ]
  },
  {
   "title": "Storage Percent",
   "type": "timeseries",
   "description": "Percent of storage space that's used. The storage that's used by the service can include database files, transaction logs, and server logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "postgresql_storage_percent{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Storage Used"
    }
   ]
  },
  {
   "title": "Backup",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Backup Storage Used",
   "type": "timeseries",
   "description": "\tAmount of backup storage used. This metric represents the sum of storage consumed by all the full database backups, differential backups, and log backups retained based on the backup retention period set for the server",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "postgresql_backup_storage_used{instance_name=~'${instance}', cluster=~\"$cluster\"}",
     "legendFormat": "Storage Used"
    }
   ]
  }
 ]
}