{{- if .Values.dbaas.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: dbaas-postgres-adapter
    name: dbaas-postgres-adapter
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: dbaas-aggregator-registration-credentials
data:
  password: {{ ( include "postgres.DBAAS_CLUSTER_DBA_CREDENTIALS_PASSWORD" . ) | b64enc }}
  username: {{ ( include "postgres.DBAAS_CLUSTER_DBA_CREDENTIALS_USERNAME" . ) | b64enc }}
type: Opaque
{{- end }}
