{{ if .Values.dbaas.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: dbaas-postgres-adapter
    name: dbaas-postgres-adapter
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: dbaas-adapter-credentials
data:
  {{ if .Values.dbaas.adapter }}
  password: {{ default "dbaas-aggregator" .Values.dbaas.adapter.password | b64enc }}
  username: {{ default "dbaas-aggregator" .Values.dbaas.adapter.username | b64enc }}
  {{ else }}
  password: {{ "dbaas-aggregator" | b64enc }}
  username: {{ "dbaas-aggregator" | b64enc }}
  {{ end }}
type: Opaque
{{ end }}
