{{ if .Values.serviceAccount.create }}
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: hook-rb
  labels:
    name: patroni-core
      {{ include "kubernetes.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation, hook-succeeded
subjects:
- kind: ServiceAccount
  name: hook-sa
roleRef:
  kind: Role
  name: hook-role
  apiGroup: rbac.authorization.k8s.io
{{ end }}
