{{- if .Values.queryExporter.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: query-exporter
    name: query-exporter
      {{ include "kubernetes.labels" . | nindent 4 }}
  name: query-exporter-user-credentials
data:
  username: {{ default "query-exporter" .Values.queryExporter.pgUser | b64enc }}
  password: {{ default "PaSsw0rDfoRExporT3r?" .Values.queryExporter.pgPassword | b64enc }}
type: Opaque
{{- end }}

{{- if .Values.postgresExporter }}
{{- if and (.Values.queryExporter.install) (.Values.postgresExporter.install) }}
{{- fail "It's not possible to install both Postgres Exporter and Query Exporter, failing the flow." }}
{{- end }}
{{- end }}
