{{ if .Values.queryExporter.install }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: query-exporter-config
  labels:
    app: query-exporter
    name: query-exporter
    {{ include "kubernetes.labels" . | nindent 4 }}
data:
  config.yaml: |
{{- include "query-exporter.queryContent" . | nindent 4 }}
  initial-config.yaml: |
{{- include "query-exporter.queryContent" . | nindent 4 }}
{{- end }}
