{{- if .Values.patroni.install }}
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: patroni
    name: patroni-rest-api-credentials
    {{ include "kubernetes.labels" . | nindent 4 }}
  name: patroni-rest-api-credentials
data:
  password: {{ ( include "patroni.restApiPassword" . ) | b64enc }}
  username: {{ ( include "patroni.restApiUser" . ) | b64enc }}
type: Opaque
{{ end }}
