{{- if .Values.backupDaemon.install }}
{{- $s3Data := fromYaml (include "backupDaemon.s3Aliases" .) }}
{{- if $s3Data.items }}
{{- $aliases := dict }}
{{- range $s3Data.items }}
{{- $out := dict }}

{{- if .spec }}
{{- $out = merge $out (omit .spec "storageBucket" "storageUsername" "storageRegion" "storageServerUrl") }}
{{- if .spec.storageBucket }}{{- $out = set $out "bucketName" .spec.storageBucket }}{{- end }}
{{- if .spec.storageUsername }}{{- $out = set $out "accessKeyId" .spec.storageUsername }}{{- end }}
{{- $out = set $out "region" (default "us-east-1" .spec.storageRegion) }}
{{- if .spec.storageServerUrl }}{{- $out = set $out "s3Url" .spec.storageServerUrl }}{{- end }}
{{- end }}

{{- if .secretContent }}
{{- $out = merge $out (omit .secretContent "storagePassword") }}
{{- if .secretContent.storagePassword }}{{- $out = set $out "accessKeySecret" .secretContent.storagePassword }}{{- end }}
{{- end }}

{{- $aliases = set $aliases .name $out }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: s3-aliases
  labels:
    app: postgres-backup-daemon
    name: postgres-backup-daemon
    {{- include "kubernetes.labels" . | nindent 4 }}
type: Opaque
stringData:
  s3_aliases.json: |
{{ $aliases | toPrettyJson | indent 4 }}
{{- end }}
{{- end }}