name: Build Artifacts
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
    inputs:
      publish_docker:
        description: "Publish image to ghcr.io/netcracker/pgskipper-operator"
        type: boolean
        default: false
        required: false

concurrency:
  group: build-and-push-${{ github.ref }}
  cancel-in-progress: true

env:
  TAG_NAME: ${{ github.event.release.tag_name || github.ref }}
  PUSH: ${{ (github.event_name != 'workflow_dispatch' || inputs.publish_docker) && github.actor != 'dependabot[bot]' }}

jobs:
  multiplatform_build:
    strategy:
      fail-fast: false
      matrix:
        component:
          - name: pgskipper-operator
            file: build/Dockerfile
            context: ""
            directory: "build"
          - name: pgskipper-operator-tests
            file: tests/Dockerfile
            context: "tests"
            directory: "tests"
          - name: pgskipper-operator-transfer
            file: docker-transfer/Dockerfile
            context: "."
            directory: "docker-transfer"
    runs-on: ubuntu-24.04
    steps:
      - name: Validate
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && "${{ github.ref }}" == refs/tags* ]]; then
            echo -e "\033[91mManual workflow run on tags is not allowed!\033[0m"
            exit 1
          fi
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # OR "2" -> To retrieve the preceding commit.
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
      # NOTE: `since_last_remote_commit: true` is implied by default and falls back to the previous local commit.
        with:
          #dir_names: 'true'
          dir_names_exclude_current_dir: 'true'
          #dir_names_max_depth: '1'
          files: ${{ matrix.component.directory }}
      - name: Skip build if no changes
        if: ${{ steps.changed-files.outputs.any_changed == 'false' }}
        run: |
          echo "No changes in ${matrix.component.directory}, skipping build."
          exit 0
      - name: Set up QEMU
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${GITHUB_ACTOR}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Prepare Tag
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: echo "TAG_NAME=$(echo ${TAG_NAME} | sed 's@refs/tags/@@;s@refs/heads/@@;s@/@_@g')" >> $GITHUB_ENV
      - name: Get package IDs for delete
        if: ${{ steps.changed-files.outputs.any_changed == 'true' && env.PUSH }}
        id: get-ids-for-delete
        uses: Netcracker/get-package-ids@v0.0.1
        with:
          component-name: ${{ matrix.component.name }}
          component-tag: ${{ env.TAG_NAME }}
          access-token: ${{secrets.GITHUB_TOKEN}}
      - name: Build and push
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: docker/build-push-action@v6
        with:
          no-cache: true
          context: ${{ matrix.component.context }}
          file: ${{ matrix.component.file }}
          platforms: linux/amd64,linux/arm64
          push: ${{ env.PUSH }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ matrix.component.name }}:${{ env.TAG_NAME }}
          provenance: false
      - uses: actions/delete-package-versions@v5
        if: ${{ steps.get-ids-for-delete.outputs.ids-for-delete != '' && steps.changed-files.outputs.any_changed == 'true' }}
        with:
          package-name: ${{ matrix.component.name }}
          package-type: 'container'
          package-version-ids: ${{ steps.get-ids-for-delete.outputs.ids-for-delete }}
