name: "MS SBOM tool"
on:
  workflow_dispatch: {}
jobs:
  sbom:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4      
      - name: Generate SBOM
        run: |
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          mkdir -p ./sbom
          $RUNNER_TEMP/sbom-tool generate -b ./sbom -bc . -pn Test -pv 1.0.0 -ps MyCompany -nsb https://sbom.mycompany.com -V Verbose

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          path: sbom
